name: Android CI

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      USERNAME_GITHUB: ${{ secrets.GITHUB_USERNAME }}
      TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew app:assembleRelease
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ProtoHax-build-${{ github.sha }}
        path: ./app/build/outputs/apk/release/app-release.apk
